sonar.projectKey=jujur10_trade_4bfea609-ad14-487c-9dd7-70a0df9dcb6c

# relative paths to source directories. More details and properties are described
# at https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/
sonar.scm.exclusions.disabled=true
sonar.sources=./src/
sonar.tests=./tests/
